# Translator MetaKGs

See: https://github.com/NCATSTranslator/Translator_component_toolkit/issues/38

2026-06-01

In [1]:
from TCT import translator_metakg, translator_query, name_resolver, TCT_neighborhood_finder, TCT_pathfinder

In [2]:
APInames, metaKG, Translator_KP_info= translator_metakg.load_translator_resources(use_new_metakg_url=True)

Skipping server without x-maturity: {'url': '/sipr'}
Skipping server without x-maturity: {'description': 'Local dev', 'url': 'http://127.0.0.1:5001'}
Skipping server without x-maturity: {'description': 'Local dev', 'url': 'http://127.0.0.1:5001'}
imProving Agent for TRAPI 1.5 - no hits found in new metakg URL, trying old URL pattern
CATRAX BigGIM DrugResponse Performance Phase KP - TRAPI 1.5.0 - no hits found in new metakg URL, trying old URL pattern
CATRAX Pharmacogenomics KP - TRAPI 1.5.0 - no hits found in new metakg URL, trying old URL pattern
OpenPredict API - no hits found in new metakg URL, trying old URL pattern
mediKanren - no hits found in new metakg URL, trying old URL pattern
Knowledge Collaboratory API - no hits found in new metakg URL, trying old URL pattern
Sri-node-normalizer(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Shepherd SIPR - no hits found in new metakg URL, trying old URL pattern
Cqs(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Aragorn(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Shepherd-arax(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Answer-coalesce(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Shepherd-aragorn(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Autonomous Relay System (ARS) TRAPI - no hits found in new metakg URL, trying old URL pattern
Shepherd-bte(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
SPOKE KP for TRAPI 1.5 - no hits found in new metakg URL, trying old URL pattern
Workflow-runner(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Sri-answer-appraiser(Trapi v1.5.0) - no hits found in new metakg URL, trying old URL pattern
Aragorn(Trapi v1.6.0) - no hits found in new metakg URL, trying old URL pattern

In [3]:
metaKG

,API,Predicate,Subject,Object,URL
0,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:Disease,biolink:Cell,https://genetics-kp.transltr.io/genetics_provi...
1,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:Cell,biolink:Disease,https://genetics-kp.transltr.io/genetics_provi...
2,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:Cell,biolink:PhenotypicFeature,https://genetics-kp.transltr.io/genetics_provi...
3,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:PhenotypicFeature,biolink:Cell,https://genetics-kp.transltr.io/genetics_provi...
4,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:Disease,biolink:Pathway,https://genetics-kp.transltr.io/genetics_provi...
...,...,...,...,...,...
31140,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:NamedThing,biolink:Disease,https://kg2cploverdb.ci.transltr.io/kg2c/query
31141,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:NamedThing,biolink:PhenotypicFeature,https://kg2cploverdb.ci.transltr.io/kg2c/query
31142,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:NamedThing,biolink:BehavioralFeature,https://kg2cploverdb.ci.transltr.io/kg2c/query
31143,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:ChemicalEntity,biolink:BehavioralFeature,https://kg2cploverdb.ci.transltr.io/kg2c/query
31144,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:MolecularMixture,biolink:BehavioralFeature,https://kg2cploverdb.ci.transltr.io/kg2c/query

In [4]:
APInames_old, metaKG_old, Translator_KP_info_old = translator_metakg.load_translator_resources(use_new_metakg_url=False)

Skipping server without x-maturity: {'url': '/sipr'}
Skipping server without x-maturity: {'description': 'Local dev', 'url': 'http://127.0.0.1:5001'}
Skipping server without x-maturity: {'description': 'Local dev', 'url': 'http://127.0.0.1:5001'}

In [5]:
metaKG_old

,API,Predicate,Subject,Object,URL
0,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:Disease,biolink:Cell,https://genetics-kp.transltr.io/genetics_provi...
1,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:Cell,biolink:Disease,https://genetics-kp.transltr.io/genetics_provi...
2,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:Cell,biolink:PhenotypicFeature,https://genetics-kp.transltr.io/genetics_provi...
3,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:PhenotypicFeature,biolink:Cell,https://genetics-kp.transltr.io/genetics_provi...
4,Genetics Data Provider for NCATS Biomedical Tr...,biolink:genetic_association,biolink:Disease,biolink:Pathway,https://genetics-kp.transltr.io/genetics_provi...
...,...,...,...,...,...
31140,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:NamedThing,biolink:Disease,https://kg2cploverdb.ci.transltr.io/kg2c/query
31141,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:NamedThing,biolink:PhenotypicFeature,https://kg2cploverdb.ci.transltr.io/kg2c/query
31142,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:NamedThing,biolink:BehavioralFeature,https://kg2cploverdb.ci.transltr.io/kg2c/query
31143,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:ChemicalEntity,biolink:BehavioralFeature,https://kg2cploverdb.ci.transltr.io/kg2c/query
31144,RTX KG2 - TRAPI 1.5.0,biolink:applied_to_treat,biolink:MolecularMixture,biolink:BehavioralFeature,https://kg2cploverdb.ci.transltr.io/kg2c/query